
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 06 09:58:21 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 24;
  public static final int Llave_c = 31;
  public static final int Op_booleano = 27;
  public static final int Llave_a = 30;
  public static final int If = 12;
  public static final int T_dato = 8;
  public static final int Real = 7;
  public static final int Formula = 39;
  public static final int Else = 13;
  public static final int Variable = 37;
  public static final int Corchete_c = 33;
  public static final int Corchete_a = 32;
  public static final int Punto = 38;
  public static final int While = 15;
  public static final int Division = 22;
  public static final int Int = 9;
  public static final int Cadena = 10;
  public static final int Parentesis_c = 29;
  public static final int Parentesis_a = 28;
  public static final int For = 16;
  public static final int P_coma = 35;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int As = 11;
  public static final int Integer = 4;
  public static final int Linea = 2;
  public static final int Char = 5;
  public static final int Op_atribucion = 25;
  public static final int ERROR = 41;
  public static final int Do = 14;
  public static final int Op_logico = 23;
  public static final int Identificador = 36;
  public static final int Resta = 20;
  public static final int Boolean = 6;
  public static final int Multiplicacion = 21;
  public static final int Igual_F = 18;
  public static final int Op_incremento = 26;
  public static final int Numero = 40;
  public static final int Suma = 19;
  public static final int Main = 34;
  public static final int Igual = 17;
  public static final int Comillas = 3;
}

